# kustomization.yml
resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.9.1/cert-manager.yaml
  - letsencrypt-clusterissuer.yml
#  - vault-clusterissuer.yml
#  - cert-manager-approle.yml
